### PR TITLE
fix: `VirtualFileEntry::Read` now works with `big` pages.

### LINKED ISSUE #6: Reading pixel data troubles.
So, I'd been poking at the example code and trying to see if I could get it running.

There's several parts to decrypting the data:

1. Parsing through blocks for 32x32
2. Checking if these blocks are activated.
3. If active, reading the size of the upcoming rle stream.
4. reading the RLE stream.
5. Decoding the RLE stream
6. manipulating the pixeldata into an appropriate format. (swizzling, converting premultiplied alpha, etc)
7. pouring final pixel data into final pixelformat container.

1 and 2 have been easy enough, and I suspect 6 and 7(7 works... with undefined colors, but it works...) are easy enough as well... once the rest works.

Sometimes, when reading the RLE stream (step 4), I sometimes get a 'stack_buffer_overflow' asan crash, pointing at the saistream in libsai:

`entry.Read(CompressedTile.data(), Size);`

``#3 0x7fe834021048 in sai::VirtualFileEntry::Read(void*, unsigned long) /home/wolthera/krita/src/plugins/impex/sai/3rdparty/libsai/source/sai.cpp:779``

I am not sure if this is happening because the Read() function is buggy, the Readme algorithm is buggy, or because there's missing functionality in VirtualFileEntry to prevent reading out of line. (The Readme algorithm, at the very least, is outdated. It tries to treat VirtualFileEntry::Read as a boolean for the while loop, which doesn't work...)

I also suspect the RLE function given is buggy, given I have frequently gotten similar crashes with the `write`/DecompressedTile.data() buffer, but I am not sure whether this is because the algorithm doesn't make sense, or that it is being fed the wrong information.

I mean, I guess if I sit down with some graph paper and a big c++ data structures book I'll eventually figure this out, but I was wondering if there's anything obvious you see when looking at your own old notes?

### PR DESCRIPTION
**Pull request by UserIsntAvailable**
Fixes #6.

First of all, thanks for the amazing for the work you did reverse engineering the sai file format. I fixed this a while back on a rewrite of the library that I did on Rust, but completely forgot to actually fix it here. TBH, if you ask me why _your_ implementation was wrong, then IDK; I came out with this as the "most logical solution" that would solve the problem and after a couple hours of debugging I was able to make it work. I left a `TODO` and a `FIXME` in here so that you can decide what you want to do with those suggestions.

### CODE REVIEW

File: samples/Document.cpp [hunk 1]
```diff
@@ -234,7 +235,7 @@ std::unique_ptr<std::uint32_t[]> ReadRasterLayer(
 	);
 
 	// 32 x 32 Tile of B8G8R8A8 pixels
-	std::array<std::uint8_t, 0x1000> CompressedTile = {};
+	std::array<std::uint8_t, 0x800> CompressedTile = {};
```
Comment (Wunkolo) [inline samples/Document.cpp:238]: How was `0x800` derived here? I have a unit-case that recreates the original crash and this seems to work with either `0x800` and `0x1000`. I have to dig up the IDA Pro file to check but I recall it reading `0x1000` bytes in-place and then decompressing it in a buffer of the same size. I could be wrong, as it's possible for an RLE stream to try and compress a worst-case stream of bytes.

File: samples/Document.cpp [hunk 2]
```diff
@@ -117,7 +117,8 @@ void ProcessLayerFile(
 		LayerFile.Read<std::uint32_t>(CurTagSize);
 		switch( CurTag )
 		{
-			case sai::Tag("name"):
+            // TODO(Unavailable): The default endianness should be `Big Endian`?
```
Comment (Wunkolo) [inline samples/Document.cpp:120]: This is the first time running into a big-endian exception to the little-endian rule. No need to consider making it the default.

File: source/sai.cpp [hunk 3]
```diff
@@ -731,66 +731,59 @@ void VirtualFileEntry::Seek(std::size_t NewOffset)
...
+            }
+            else
+            {
+                Read = LeftToRead;
+                PageOffset += Read;
+            }
+
+            char* Bytes = new char[Read];
+            // FIXME(Unavailable): If an error occurs while reading ( or seeking ) there is
+            //  currently no way that a user could now it. Maybe return 0 or -1?
```
Comment (Wunkolo) [inline source/sai.cpp:761]: No need to worry about this. `SaiStream` is an `std::ifstream`. So in the case of a failure, `SaiStream` will turn into a fail-state and all further operations will do nothing and `SaiStream`'s implicit `bool` cast will return false, hence the common pattern of doing `if( SaiStream )` and `while( SaiStream )`.

I'd rather keep that pattern consistent(admittedly, this is old embarrassing code I wrote in my college-days and I would never allow myself to do this pattern of inheriting an `ifstream`, but this bug is what held me back from doing a large re-write away from this kind of pattern).

File: source/sai.cpp [hunk 4]
```diff
@@ -731,66 +731,59 @@ void VirtualFileEntry::Seek(std::size_t NewOffset)
...
+            SaiStream->read(Bytes, Read);
+            std::size_t BytesWrote = Size - LeftToRead;
+            std::memmove(
```
Comment (Wunkolo) [inline source/sai.cpp:764]: The two pointer ranges will never overlap, so a `std::memcpy` is fine here.

File: source/sai.cpp [hunk 5]
```diff
@@ -731,66 +731,59 @@ void VirtualFileEntry::Seek(std::size_t NewOffset)
...
+                PageOffset = 0;
+                NeedsNextPage = true;
+            }
+            else
+            {
+                Read = LeftToRead;
+                PageOffset += Read;
+            }
+
+            char* Bytes = new char[Read];
```
Comment (Wunkolo) [inline source/sai.cpp:759]: This is never deleted and is a memory leak. This is also a very old c-style allocation and should probably be a `std::vector<char>` or `std::unique_ptr<char[]>`.

**Review by Wunkolo — COMMENTED** [review]
Wow, thank you for fixing this age old bug! This bug is basically what kept me from doing a re-write and moving on to making a similar library for Sai 2 and kept me from ever feeling like this library was ever "MVP". With this now I can allow myself to do some more stronger re-writing to something more C++20-like and dive further into figuring out how masks and vector-layers and such work.

You're right, just from a glance, I can't explain what makes the new code work over the old one necessarily, but it does absolutely fix the issue. I have a small unit-test file that recreates the issue, and after implementing the change in `sai.cpp`, it seems to fix it:

Before:
```
./Document SampleFiles/testfile_09_masks_small.sai
Width: 512 Height: 512
        - "00000008"
        - "00000002"
(crash)
```

After:
```
./Document SampleFiles/testfile_09_masks_small.sai
Width: 512 Height: 512
        - "00000008"
        - "00000002"
        - "00000003"
        - "00000006"
        - "00000009"
        - "00000004"
        - "00000005"
        - "00000007"
Iterated Document of SampleFiles/testfile_09_masks_small.sai in 387379087 ns
```

Again thank you!

File: samples/Document.cpp (hunk 1 above)
Comment (UserIsntAvailable) [reply samples/Document.cpp:238]: The old example that was on the README was using an `0x800` array. I remember that when I was writing my implementation, the compressed buffer never needed more than `0x800`, so I decided to follow the implementation that you wrote on the README, but then I read the implementation that you wrote on `Document.cpp` and saw `0x1000` and was really confused, because I haven't yet find an instance were a buffer that large is needed.

I don't think it really matters if it is `0x800` or `0x1000`, but just to be safe it will be better to leave it at `0x1000` if you are not sure about it for the moment.

File: samples/Document.cpp (hunk 2 above)
Comment (UserIsntAvailable) [reply samples/Document.cpp:120]: Yeah I should have checked the usages of `Tag`, it seems that only serial streams use Big Endian.

File: source/sai.cpp (hunk 3 above)
Comment (UserIsntAvailable) [reply source/sai.cpp:761]: OK, I found kinda odd that there wasn't any error handling for this calls, but that make sense. :+1:

File: source/sai.cpp (hunk 4 above)
Comment (UserIsntAvailable) [reply source/sai.cpp:764]: Exposing that I'm not cpp developer xD. Anyways I should have definitely search the differences between both instead of just blindly thinking than `moving > copying`.

File: samples/Document.cpp (hunk 1 above)
Comment (Wunkolo) [reply samples/Document.cpp:238]: I'm not sure about it at the moment. Without digging into the old IDA Pro file, I vaguely remember something about the size of the compressed/uncompressed buffer as well. Something about it using a singular 0x1000-byte buffer and having both the compressed possibly 0x800-sized RLE stream and decompressed data using this same buffer in-place, but I'll leave it untouched for now until I can verify it myself.

File: source/sai.cpp (hunk 5 above)
Comment (UserIsntAvailable) [reply source/sai.cpp:759]: _Another cpp newbie mistake_. I went ahead and also improved it ( I think ) a bit; instead of creating a new buffer on every loop I'm now reusing the same buffer for every `read` call.

**Comment by UserIsntAvailable** [comment]
Ok I made the needed changes.

> Looks like the diff is not that insightful on the line-by-line differences since all the tabs got converted into spaces.
Now everything makes sense, I was super confused why the diff wasn't working. Anyways, I converted everything to tabs with tab size 8, everything should be good now.

File: samples/Document.cpp (hunk 1 above)
Comment (UserIsntAvailable) [reply samples/Document.cpp:237]: Ok, I will change it back to `0x1000`, seems to be the safest solution.

**Comment by UserIsntAvailable** [comment]
Ok, I changed the compressed buffer size to `0x1000`; the code still works with that size anyways, and it could be later changed just for "correctness".

**Comment by Wunkolo** [comment]
> Anyways, I converted everything to tabs with tab size 8, everything should be good now.

For sure, that cleaned it up a bunch. All my editors use 4-space tabs by default and I have it set to 4-spaces [on GitHub as well](https://github.com/settings/appearance)(Not sure why [GitHub chooses 8-space tabs by default](https://twitter.com/martinwoodward/status/1441045645582811138). That's super huge).

> Ok, I changed the compressed buffer size to 0x1000; the code still works with that size anyways, and it could be later changed to 0x800 if it is confirmed that is enough, just for "correctness".

Thank you! I've added some continuous-integration builds for win(x32,x64,arm64), macos(x64,arm64), and linux(x64) since you've started this pr to help verify builds. The rest of the changes I'd like are mostly stylization(I intend to add a `.clang-format` to make contributions easier) or nit-picks that don't really change the principal of the implementation.
